Fix Bugs
AY2324S2-CS2103T-T09-4/tp pull request #235
Opened 2024-04-10 06:16 UTC by qinxutan

Fixes #225, #224, #223, #222, #221, #220, #219, #214, #208, #207, #205, #203, #194, #192, #183

2024-04-11 13:35 UTC, whelan-low requested changes
LGTM so far! However, just want to check for the rest of the commands that don't seem to be changed:
Add, Edit, Delete student (from TAHelper itself): Do they work as intended with the UI?
Delete module: Does the module pane need to be updated? (Same for Add/Delete class)

2024-04-11 13:35 UTC, whelan-low commented on src/main/java/seedu/address/logic/commands/AddTeamCommand.java
> +                                          int teamSize) {
Is the whitespace here necessary?

2024-04-12 04:18 UTC, qinxutan commented
> LGTM so far! However, just want to check for the rest of the commands that don't seem to be changed: Add, Edit, Delete student (from TAHelper itself): Do the student details need to be updated in the UI? Delete module: Does the module pane need to be updated? (Same for Add/Delete class)

yep the module pane updates for delete module/add/delete class under the usemoduleview
as for the student, the personlist is updated when thrs any changes made to student and then usepersonview

2024-04-12 04:18 UTC, qinxutan commented on src/main/java/seedu/address/logic/commands/AddTeamCommand.java
> +                                          int teamSize) {
ok will fix!

2024-04-12 04:56 UTC, merged